dependencies:
#  - name: mattermost-db
#    version: 0.2.6
#    repository: https://releases.mattermost.com/helm
#    tags:
#      - core
  - name: grafana
    version: 0.6.1
    repository: "alias:stable" #https://kubernetes-charts.storage.googleapis.com 
    tags:
      - metrics
      - loadtest
#  - name: mattermost-loadtest
#    version: 0.1.0
#    repository: https://releases.mattermost.com/helm
#    tags:
#      - loadtest
  - name: prometheus
    version: 5.1.0
    repository: "alias:stable"
    tags:
      - metrics
      - loadtest
#  - name: mattermost-proxy
#    version: 0.1.0
#    repository: "alias:mattermost" #https://releases.mattermost.com/helm
#    tags:
#      - core
  - name: minio
    version: 0.5.2
    repository: "alias:stable"
    tags:
      - core
