global:
  dbRootPassword: "rootpasswd"
  dbUser: "mmuser"
  dbPassword: "passwd"
  dbName: "mattermost"
  filesAccessKey: "AKIAIOSFODNN7EXAMPMM"
  filesSecretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKMM"
  mattermostLicense: "THIS STRING SHOULD BE REPLACED WITH THE CONTENTS OF YOUR LICENSE FILE"
  features:
    elasticsearch: false
  sendPushNotifications: false

tags:
  core: true
  metrics: true
  loadtest: false

mattermost-app:
  replicaCount: 2
  image:
    tag: daily-build
  jobserver:
    enabled: enabled
    replicaCount: 2

mattermost-proxy:
  replicaCount: 2

mattermost-elasticsearch:
  client:
    replicaCount: 2
  master:
    replicaCount: 3
  data:
    replicaCount: 2

mattermost-loadtest:
  numTeams: 1
  numChannelsPerTeam: 4000
  numUsers: 5000
  testLengthMinutes: 20
  numActiveEntities: 5000
  actionRateMilliseconds: 60000
  actionRateMaxVarianceMilliseconds: 15000
  pprofDelayMinutes: 15
  pprofLengthSeconds: 240
  sendReportToMMServer: false
  resultsServerUrl: ""
  resultsChannelId: ""
  resultsUsername: ""
  resultsPassword: ""

mattermost-push-proxy:
  replicaCount: 2
  applePushSettings:
    apple:
      configMap: "apple-cert-path"
      privateCert: ""
      privateCertPassword: ""
      pushTopic: "com.mattermost.Mattermost"
    apple_rn:
      configMap: "apple-rn-cert-path"
      privateCert: ""
      privateCertPassword: ""
      pushTopic: "com.mattermost.react.native"
    apple_rnbeta:
      configMap: "apple-rnbeta-cert-path"
      privateCert: ""
      privateCertPassword: ""
      pushTopic: ""
  androidPushSettings:
    android:
      apiKey: ""
    android_rn: 
      apiKey: ""

grafana:
  server:
    service:
      type: LoadBalancer
    persistentVolume:
      enabled: false
    adminPassword: "admin"
    setDatasource:
      enabled: true
      datasource: 
        name: ${DS_MATTERMOST}

prometheus:
  alertmanager:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  server:
    persistentVolume:
      enabled: false
    service:
      servicePort: 9090
  serverFiles:
    prometheus.yml: 
      rule_files:
        - /etc/config/rules
        - /etc/config/alerts
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
              - localhost:9090
        - job_name: 'mattermost-app'
          scrape_interval: 5s
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              regex: (.+):(?:\d+);(\d+)
              replacement: ${1}:${2}
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              #regex: __meta_kubernetes_pod_label_app(.*)
              target_label: kubernetes_pod_name
