apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
          - mountPath: /config/config.json
            name: push-config-json
            subPath: push-config.json
          {{- if .Values.apns.configMap }}
          - mountPath: /certs/apple-push-cert.pem
            name: apple-push-cert 
            subPath: apple-push-cert.pem
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
        - name: push-config-json
          configMap:
            name: {{template "fullname" .}}-push-config-json
            items:
            - key: push-config.json
              path: push-config.json
        {{- if .Values.apns.configMap }}
        - name: apple-push-cert
          configMap:
            name: {{template "fullname" .}}-{{ .Values.apns.configMap }}
            items:
            - key: apple-push-cert.pem
              path: apple-push-cert.pem
        {{- end }}

